#!/bin/bash

## Inspired by https://github.com/andrewseidl/githook-clang-format/blob/master/ 
## Runs tests then formats the source files


printf "Running tests..."
./run_tests.sh > /dev/null

if [ $? -ne 0 ]; then
    printf "Some tests failed. Aborting commit...\n"
    exit 1
fi

printf "ok\n"


find_binary() {
    binary=$(echo -e ${PATH//:/\\n} | 
            while read line; do find "$line" -name "$1*"; done | 
            sort -n | 
            head -n 1)
    echo $binary
}

clang_format=$(find_binary clang-format)

if [ -z $clang_format ]; then 
    echo "clang format not found, aborting.."
    exit 1
fi


format_file() {
  file="${1}"
  if [ -f $file ]; then
    $clang_format -i -style=file ${1}
    git add ${1}
  fi
}

case "${1}" in
  --about )
    echo "Runs clang-format on the source files"
    ;;
  * )
    for file in `git diff-index --cached --name-only HEAD | grep -iE '\.(cpp|cc|h|hpp)$' ` ; do
      format_file "${file}"
    done
    ;;
esac